# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\angel\Desktop\Nuevo proyecto\Gui\proyectoDataBase\new_interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1166, 815)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("/* #################Estilo para mi header ##################*/\n"
"/* Estilo para los botones de control (cerrar, maximizar, minimizar) */\n"
"#bt_conexion,\n"
"#bt_cerrar,\n"
"#bt_maximizar,\n"
"#bt_minimizar {\n"
"    background-color: #38759a; /* Color de fondo por defecto */\n"
"    color: white; /* Color del texto */\n"
"    width: 12px; /* Ancho del botón */\n"
"    height: 12px; /* Alto del botón */\n"
"    border: 2px solid #000; /* Borde negro */\n"
"    padding: 10px; /* Espaciado interno */\n"
"    text-align: center; /* Alineación del texto */\n"
"    text-decoration: none; /* Sin subrayado */\n"
"    display: inline-block;\n"
"    cursor: pointer; /* Cambia el cursor al pasar el ratón */\n"
"    border-radius: 10px; /* Bordes circulares */\n"
"    transition: background-color 0.3s, border-color 0.3s; /* Transiciones al hacer hover */\n"
"}\n"
"\n"
"/* Efecto hover para los botones de control */\n"
"#bt_conexion:hover,\n"
"#bt_cerrar:hover,\n"
"#bt_maximizar:hover,\n"
"#bt_minimizar:hover {\n"
"    background-color:#8fa8af; /* Color de fondo al hacer hover */\n"
"}\n"
"\n"
"/* Estilo para el contenedor fr_header */\n"
"#fr_header {\n"
"    background-color: #38759a; /* Color de fondo del contenedor */\n"
"    padding:; /* Añadir espacio interno al contenedor */\n"
"}\n"
"\n"
"/* Estilo para QLabel con la clase lb_bd */\n"
"#lb_bd {\n"
"    font-size: 18px; /* Tamaño de fuente */\n"
"    color: #555; /* Color del texto */\n"
"    margin-bottom: 20px; /* Márgen inferior */\n"
"}\n"
"\n"
"/* #################Estilo para el menu ##################*/\n"
"\n"
"#bt_agregar,\n"
"#bt_editar,\n"
"#bt_eliminar,\n"
"#bt_info {\n"
"    background-color: #38759a; /* Color de fondo por defecto */    \n"
"    height: 24px;\n"
"    color: white; /* Color del texto */\n"
"    border: 0px solid #000; /* Borde negro */\n"
"    padding: 10px; /* Espaciado interno */\n"
"    text-align: center; /* Alineación del texto */\n"
"    text-decoration: none; /* Sin subrayado */\n"
"    display: inline-block;\n"
"    font-size: 16px; /* Tamaño de fuente */\n"
"    text-align: left;\n"
"    margin: 0; /* Eliminar márgenes externos */\n"
"    cursor: Pointing Hand; /* Cambia el cursor al pasar el ratón */\n"
"    border-top-right-radius: 20px; /* Borde redondeado en la esquina superior derecha */\n"
"    border-bottom-right-radius: 20px; /* Borde redondeado en la esquina inferior derecha */\n"
"    transition: background-color 0.3s, border-color 0.3s; /* Transiciones al hacer hover */\n"
"}\n"
"\n"
"/* Efecto hover para los botones del menú */\n"
"#bt_agregar:hover,\n"
"#bt_editar:hover,\n"
"#bt_eliminar:hover,\n"
"#bt_info:hover {\n"
"    background-color: #8fa8af; /* Color de fondo más oscuro al hacer hover */\n"
"    border-color: #000; /* Borde negro al hacer hover */\n"
"    color: black;\n"
"    border: 2px solid #000;\n"
"}\n"
"#stackedw {\n"
"    background: #8fa8af;\n"
"}\n"
"\n"
"/* Estilo para el ComboBox con la clase cb_tabla */\n"
"#cb_tabla {\n"
"    font-size: 20px;\n"
"    padding: 8px;\n"
"    border: 0px solid #ccc;\n"
"    border-radius: 10px;\n"
"    border-top-left-radius: 18px;\n"
"    border-bottom-left-radius: 18px;\n"
"    background-color: #fff;\n"
"    color: #333;\n"
"    outline: none;\n"
"    height: 25px;\n"
"    cursor: pointer;\n"
"    selection-background-color: #38759a; /* Color de fondo al seleccionar una opción */\n"
"    selection-color: #fff; /* Color del texto al seleccionar una opción */\n"
"}\n"
"\n"
"/* #################Estilo para el fr_container ###############*/\n"
"#fr_tabla {\n"
"    background: #d3c392; \n"
"}\n"
"#fr_container {\n"
"    background: blaack; \n"
"}\n"
"\n"
"/* Estilo para el botón bt_refrescar */\n"
"#bt_refrescar {\n"
"    background-color: #415c05; /* Color de fondo por defecto */\n"
"    color: white; /* Color del texto */\n"
"    border-radius: 20px; /* Bordes redondeados */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"    cursor: pointer; /* Cambia el cursor al pasar el ratón */\n"
"    transition: background-color 0.3s, color 0.3s; /* Transiciones al hacer hover */\n"
"}\n"
"\n"
"/* Efecto hover para el botón bt_refrescar */\n"
"#bt_refrescar:hover {\n"
"    background-color: #8b8652; /* Color de fondo más oscuro al hacer hover */\n"
"    color: white; /* Cambia el color del texto al hacer hover */\n"
"}\n"
"\n"
"/* Estilo para el botón bt_refrescar */\n"
"#bt_menu {\n"
"    background-color: #415c05; /* Color de fondo por defecto */\n"
"    height: 30px;\n"
"    color: white; /* Color del texto */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"    cursor: pointer; /* Cambia el cursor al pasar el ratón */\n"
"    transition: background-color 0.3s, color 0.3s; /* Transiciones al hacer hover */\n"
"    border-top-left-radius: 23px; /* Borde redondeado en la esquina superior derecha */\n"
"    border-bottom-left-radius: 23px; /* Borde redondeado en la esquina inferior derecha */\n"
"}\n"
"\n"
"/* Efecto hover para el botón bt_refrescar */\n"
"#bt_menu:hover {\n"
"    background-color: #8b8652; /* Color de fondo más oscuro al hacer hover */\n"
"    color: white; /* Cambia el color del texto al hacer hover */\n"
"}\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fr_header = QtWidgets.QFrame(self.centralwidget)
        self.fr_header.setMaximumSize(QtCore.QSize(16777215, 60))
        self.fr_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_header.setObjectName("fr_header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fr_header)
        self.horizontalLayout.setContentsMargins(5, 2, 0, 2)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_conexion = QtWidgets.QPushButton(self.fr_header)
        self.bt_conexion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_conexion.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/database.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_conexion.setIcon(icon)
        self.bt_conexion.setObjectName("bt_conexion")
        self.horizontalLayout.addWidget(self.bt_conexion)
        spacerItem = QtWidgets.QSpacerItem(992, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bt_minimizar = QtWidgets.QPushButton(self.fr_header)
        self.bt_minimizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_minimizar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_minimizar.setIcon(icon1)
        self.bt_minimizar.setObjectName("bt_minimizar")
        self.horizontalLayout.addWidget(self.bt_minimizar)
        self.bt_maximizar = QtWidgets.QPushButton(self.fr_header)
        self.bt_maximizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_maximizar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/credit-card.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_maximizar.setIcon(icon2)
        self.bt_maximizar.setObjectName("bt_maximizar")
        self.horizontalLayout.addWidget(self.bt_maximizar)
        self.bt_cerrar = QtWidgets.QPushButton(self.fr_header)
        self.bt_cerrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_cerrar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_cerrar.setIcon(icon3)
        self.bt_cerrar.setObjectName("bt_cerrar")
        self.horizontalLayout.addWidget(self.bt_cerrar)
        self.verticalLayout.addWidget(self.fr_header)
        self.fr_container = QtWidgets.QFrame(self.centralwidget)
        self.fr_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_container.setObjectName("fr_container")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fr_container)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fr_tabla = QtWidgets.QFrame(self.fr_container)
        self.fr_tabla.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_tabla.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_tabla.setObjectName("fr_tabla")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fr_tabla)
        self.verticalLayout_2.setContentsMargins(40, 11, 40, 40)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(10, 10, 0, 10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.lb_nombre_tabla = QtWidgets.QLabel(self.fr_tabla)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(20)
        self.lb_nombre_tabla.setFont(font)
        self.lb_nombre_tabla.setObjectName("lb_nombre_tabla")
        self.horizontalLayout_3.addWidget(self.lb_nombre_tabla)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.bt_menu = QtWidgets.QPushButton(self.fr_tabla)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bt_menu.setFont(font)
        self.bt_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/align-right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_menu.setIcon(icon4)
        self.bt_menu.setObjectName("bt_menu")
        self.horizontalLayout_3.addWidget(self.bt_menu)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.tb_container = QtWidgets.QTableWidget(self.fr_tabla)
        self.tb_container.setObjectName("tb_container")
        self.tb_container.setColumnCount(0)
        self.tb_container.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tb_container)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(10, 10, 0, 10)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lb_msgerror = QtWidgets.QLabel(self.fr_tabla)
        self.lb_msgerror.setMinimumSize(QtCore.QSize(250, 0))
        self.lb_msgerror.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_msgerror.setFont(font)
        self.lb_msgerror.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_msgerror.setObjectName("lb_msgerror")
        self.horizontalLayout_4.addWidget(self.lb_msgerror)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.bt_refrescar = QtWidgets.QPushButton(self.fr_tabla)
        self.bt_refrescar.setMaximumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bt_refrescar.setFont(font)
        self.bt_refrescar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/refresh-cw.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_refrescar.setIcon(icon5)
        self.bt_refrescar.setObjectName("bt_refrescar")
        self.horizontalLayout_4.addWidget(self.bt_refrescar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addWidget(self.fr_tabla)
        self.fr_menu = QtWidgets.QFrame(self.fr_container)
        self.fr_menu.setMinimumSize(QtCore.QSize(400, 0))
        self.fr_menu.setMaximumSize(QtCore.QSize(400, 16777215))
        self.fr_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_menu.setObjectName("fr_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.fr_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedw = QtWidgets.QStackedWidget(self.fr_menu)
        self.stackedw.setObjectName("stackedw")
        self.page_menu = QtWidgets.QWidget()
        self.page_menu.setObjectName("page_menu")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_menu)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 20, -1, 35)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.page_menu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.cb_tabla = QtWidgets.QComboBox(self.page_menu)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.cb_tabla.setFont(font)
        self.cb_tabla.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cb_tabla.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cb_tabla.setObjectName("cb_tabla")
        self.cb_tabla.addItem("")
        self.cb_tabla.addItem("")
        self.cb_tabla.addItem("")
        self.cb_tabla.addItem("")
        self.verticalLayout_4.addWidget(self.cb_tabla)
        spacerItem4 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem4)
        self.label_2 = QtWidgets.QLabel(self.page_menu)
        self.label_2.setMinimumSize(QtCore.QSize(60, 30))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.bt_agregar = QtWidgets.QPushButton(self.page_menu)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.bt_agregar.setFont(font)
        self.bt_agregar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/chevron-right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_agregar.setIcon(icon6)
        self.bt_agregar.setObjectName("bt_agregar")
        self.verticalLayout_4.addWidget(self.bt_agregar)
        self.bt_editar = QtWidgets.QPushButton(self.page_menu)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.bt_editar.setFont(font)
        self.bt_editar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_editar.setIcon(icon6)
        self.bt_editar.setObjectName("bt_editar")
        self.verticalLayout_4.addWidget(self.bt_editar)
        self.bt_eliminar = QtWidgets.QPushButton(self.page_menu)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.bt_eliminar.setFont(font)
        self.bt_eliminar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_eliminar.setIcon(icon6)
        self.bt_eliminar.setObjectName("bt_eliminar")
        self.verticalLayout_4.addWidget(self.bt_eliminar)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.label_3 = QtWidgets.QLabel(self.page_menu)
        self.label_3.setMinimumSize(QtCore.QSize(0, 40))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.bt_info = QtWidgets.QPushButton(self.page_menu)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.bt_info.setFont(font)
        self.bt_info.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_info.setIcon(icon6)
        self.bt_info.setObjectName("bt_info")
        self.verticalLayout_4.addWidget(self.bt_info)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.stackedw.addWidget(self.page_menu)
        self.page_agg_arbitro = QtWidgets.QWidget()
        self.page_agg_arbitro.setObjectName("page_agg_arbitro")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_agg_arbitro)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.fr_arbitro = QtWidgets.QFrame(self.page_agg_arbitro)
        self.fr_arbitro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_arbitro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_arbitro.setObjectName("fr_arbitro")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.fr_arbitro)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.fr_arbitro)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.lineEdit_nombre = QtWidgets.QLineEdit(self.fr_arbitro)
        self.lineEdit_nombre.setObjectName("lineEdit_nombre")
        self.verticalLayout_7.addWidget(self.lineEdit_nombre)
        self.label_5 = QtWidgets.QLabel(self.fr_arbitro)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.lineEdit_apellido = QtWidgets.QLineEdit(self.fr_arbitro)
        self.lineEdit_apellido.setObjectName("lineEdit_apellido")
        self.verticalLayout_7.addWidget(self.lineEdit_apellido)
        self.label_6 = QtWidgets.QLabel(self.fr_arbitro)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.lineEdit_pais = QtWidgets.QLineEdit(self.fr_arbitro)
        self.lineEdit_pais.setObjectName("lineEdit_pais")
        self.verticalLayout_7.addWidget(self.lineEdit_pais)
        self.label_7 = QtWidgets.QLabel(self.fr_arbitro)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.lineEdit_pasaporte = QtWidgets.QLineEdit(self.fr_arbitro)
        self.lineEdit_pasaporte.setObjectName("lineEdit_pasaporte")
        self.verticalLayout_7.addWidget(self.lineEdit_pasaporte)
        self.label_8 = QtWidgets.QLabel(self.fr_arbitro)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.lineEdit_inicio = QtWidgets.QLineEdit(self.fr_arbitro)
        self.lineEdit_inicio.setObjectName("lineEdit_inicio")
        self.verticalLayout_7.addWidget(self.lineEdit_inicio)
        self.label_9 = QtWidgets.QLabel(self.fr_arbitro)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.cb_reemplazo = QtWidgets.QComboBox(self.fr_arbitro)
        self.cb_reemplazo.setObjectName("cb_reemplazo")
        self.verticalLayout_7.addWidget(self.cb_reemplazo)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem6)
        self.pushButton = QtWidgets.QPushButton(self.fr_arbitro)
        self.pushButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/arrow-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon7)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_8.addWidget(self.pushButton)
        self.verticalLayout_9.addWidget(self.fr_arbitro)
        self.stackedw.addWidget(self.page_agg_arbitro)
        self.verticalLayout_3.addWidget(self.stackedw)
        self.horizontalLayout_2.addWidget(self.fr_menu)
        self.verticalLayout.addWidget(self.fr_container)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedw.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb_nombre_tabla.setText(_translate("MainWindow", "Nombre de la tabla"))
        self.bt_menu.setText(_translate("MainWindow", "Menu"))
        self.lb_msgerror.setText(_translate("MainWindow", "VALIDACIONES"))
        self.bt_refrescar.setText(_translate("MainWindow", "Refrescar "))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/icons/icons/users.svg\"/></p></body></html>"))
        self.cb_tabla.setItemText(0, _translate("MainWindow", "Seleccione la tabla"))
        self.cb_tabla.setItemText(1, _translate("MainWindow", "Árbitro"))
        self.cb_tabla.setItemText(2, _translate("MainWindow", "Partido"))
        self.cb_tabla.setItemText(3, _translate("MainWindow", "Estadio"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/icons/icons/clipboard.svg\"/></p></body></html>"))
        self.bt_agregar.setText(_translate("MainWindow", "Agregar"))
        self.bt_editar.setText(_translate("MainWindow", "Editar"))
        self.bt_eliminar.setText(_translate("MainWindow", "Eliminar"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/icons/icons/info.svg\"/></p></body></html>"))
        self.bt_info.setText(_translate("MainWindow", "Info.."))
        self.label_4.setText(_translate("MainWindow", "Nombre:"))
        self.label_5.setText(_translate("MainWindow", "Apellido:"))
        self.label_6.setText(_translate("MainWindow", "País:"))
        self.label_7.setText(_translate("MainWindow", "Pasaporte"))
        self.label_8.setText(_translate("MainWindow", "Inicio (Año):"))
        self.label_9.setText(_translate("MainWindow", "Reemplazo:"))
import icons_rc
