# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\angel\Desktop\Nuevo proyecto\Gui\proyectoDataBase\new_interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1166, 815)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("/* #################Estilo para mi header ##################*/\n"
"/* Estilo para los botones de control (cerrar, maximizar, minimizar) */\n"
"#bt_conexion,\n"
"#bt_cerrar,\n"
"#bt_maximizar,\n"
"#bt_minimizar {\n"
"    background-color: #38759a; /* Color de fondo por defecto */\n"
"    color: white; /* Color del texto */\n"
"    width: 12px; /* Ancho del botón */\n"
"    height: 12px; /* Alto del botón */\n"
"    border: 2px solid #000; /* Borde negro */\n"
"    padding: 10px; /* Espaciado interno */\n"
"    text-align: center; /* Alineación del texto */\n"
"    text-decoration: none; /* Sin subrayado */\n"
"    display: inline-block;\n"
"    cursor: pointer; /* Cambia el cursor al pasar el ratón */\n"
"    border-radius: 10px; /* Bordes circulares */\n"
"    transition: background-color 0.3s, border-color 0.3s; /* Transiciones al hacer hover */\n"
"}\n"
"\n"
"/* Efecto hover para los botones de control */\n"
"#bt_conexion:hover,\n"
"#bt_cerrar:hover,\n"
"#bt_maximizar:hover,\n"
"#bt_minimizar:hover {\n"
"    background-color:#8fa8af; /* Color de fondo al hacer hover */\n"
"}\n"
"\n"
"/* Estilo para el contenedor fr_header */\n"
"#fr_header {\n"
"    background-color: #38759a; /* Color de fondo del contenedor */\n"
"    padding:; /* Añadir espacio interno al contenedor */\n"
"}\n"
"\n"
"/* Estilo para QLabel con la clase lb_bd */\n"
"#lb_bd {\n"
"    font-size: 18px; /* Tamaño de fuente */\n"
"    color: #555; /* Color del texto */\n"
"    margin-bottom: 20px; /* Márgen inferior */\n"
"}\n"
"\n"
"/* #################Estilo para el menu ##################*/\n"
"\n"
"#bt_agregar,\n"
"#bt_editar,\n"
"#bt_eliminar,\n"
"#bt_info {\n"
"    background-color: #38759a; /* Color de fondo por defecto */    \n"
"    height: 24px;\n"
"    color: white; /* Color del texto */\n"
"    border: 0px solid #000; /* Borde negro */\n"
"    padding: 10px; /* Espaciado interno */\n"
"    text-align: center; /* Alineación del texto */\n"
"    text-decoration: none; /* Sin subrayado */\n"
"    display: inline-block;\n"
"    font-size: 16px; /* Tamaño de fuente */\n"
"    text-align: left;\n"
"    margin: 0; /* Eliminar márgenes externos */\n"
"    cursor: Pointing Hand; /* Cambia el cursor al pasar el ratón */\n"
"    border-top-right-radius: 20px; /* Borde redondeado en la esquina superior derecha */\n"
"    border-bottom-right-radius: 20px; /* Borde redondeado en la esquina inferior derecha */\n"
"    transition: background-color 0.3s, border-color 0.3s; /* Transiciones al hacer hover */\n"
"}\n"
"\n"
"/* Efecto hover para los botones del menú */\n"
"#bt_agregar:hover,\n"
"#bt_editar:hover,\n"
"#bt_eliminar:hover,\n"
"#bt_info:hover {\n"
"    background-color: #8fa8af; /* Color de fondo más oscuro al hacer hover */\n"
"    border-color: #000; /* Borde negro al hacer hover */\n"
"    color: black;\n"
"    border: 2px solid #000;\n"
"}\n"
"#stackedw {\n"
"    background: #8fa8af;\n"
"}\n"
"\n"
"/* Estilo para el ComboBox con la clase cb_tabla */\n"
"#cb_tabla {\n"
"    font-size: 20px;\n"
"    padding: 8px;\n"
"    border: 0px solid #ccc;\n"
"    border-radius: 10px;\n"
"    border-top-left-radius: 18px;\n"
"    border-bottom-left-radius: 18px;\n"
"    background-color: #fff;\n"
"    color: #333;\n"
"    outline: none;\n"
"    height: 25px;\n"
"    cursor: pointer;\n"
"    selection-background-color: #38759a; /* Color de fondo al seleccionar una opción */\n"
"    selection-color: #fff; /* Color del texto al seleccionar una opción */\n"
"}\n"
"\n"
"/* #################Estilo para el fr_container ###############*/\n"
"#fr_tabla {\n"
"    background: #d3c392; \n"
"}\n"
"#fr_container {\n"
"    background: blaack; \n"
"}\n"
"\n"
"/* Estilo para el botón bt_refrescar */\n"
"#bt_refrescar {\n"
"    background-color: #077110; /* Color de fondo por defecto */\n"
"    color: white; /* Color del texto */\n"
"    border-radius: 20px; /* Bordes redondeados */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"    cursor: pointer; /* Cambia el cursor al pasar el ratón */\n"
"    transition: background-color 0.3s, color 0.3s; /* Transiciones al hacer hover */\n"
"}\n"
"\n"
"/* Efecto hover para el botón bt_refrescar */\n"
"#bt_refrescar:hover {\n"
"    background-color: #8b8652; /* Color de fondo más oscuro al hacer hover */\n"
"    color: white; /* Cambia el color del texto al hacer hover */\n"
"}\n"
"\n"
"/* Estilo para el botón bt_refrescar */\n"
"#bt_menu {\n"
"    background-color: #077110; /* Color de fondo por defecto */\n"
"    height: 30px;\n"
"    color: white; /* Color del texto */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"    cursor: pointer; /* Cambia el cursor al pasar el ratón */\n"
"    transition: background-color 0.3s, color 0.3s; /* Transiciones al hacer hover */\n"
"    border-top-left-radius: 23px; /* Borde redondeado en la esquina superior derecha */\n"
"    border-bottom-left-radius: 23px; /* Borde redondeado en la esquina inferior derecha */\n"
"}\n"
"\n"
"/* Efecto hover para el botón bt_refrescar */\n"
"#bt_menu:hover {\n"
"    background-color: #8b8652; /* Color de fondo más oscuro al hacer hover */\n"
"    color: white; /* Cambia el color del texto al hacer hover */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #F2F2F2; /* Fondo más claro para destacar */\n"
"    color: #333; /* Color de texto oscuro para mayor legibilidad */\n"
"    font-size: 18px; /* Tamaño de fuente más estándar */\n"
"    border: 1px solid #8fa8af; /* Borde más suave */\n"
"    padding: 4px; /* Añadir un poco de espacio alrededor del texto */\n"
"    text-align: center; /* Centrar el texto */\n"
"}\n"
"\n"
"QTableWidget {\n"
"    alternate-background-color: #EBEBEB; /* Fondo alternativo más claro para mejorar la legibilidad de las filas */\n"
"}\n"
"\n"
"QTableView {\n"
"    gridline-color: #8fa8af; /* Color de las líneas de cuadrícula */\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fr_header = QtWidgets.QFrame(self.centralwidget)
        self.fr_header.setMaximumSize(QtCore.QSize(16777215, 60))
        self.fr_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_header.setObjectName("fr_header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fr_header)
        self.horizontalLayout.setContentsMargins(5, 2, 0, 2)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_conexion = QtWidgets.QPushButton(self.fr_header)
        self.bt_conexion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_conexion.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/database.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_conexion.setIcon(icon)
        self.bt_conexion.setObjectName("bt_conexion")
        self.horizontalLayout.addWidget(self.bt_conexion)
        spacerItem = QtWidgets.QSpacerItem(992, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bt_minimizar = QtWidgets.QPushButton(self.fr_header)
        self.bt_minimizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_minimizar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_minimizar.setIcon(icon1)
        self.bt_minimizar.setObjectName("bt_minimizar")
        self.horizontalLayout.addWidget(self.bt_minimizar)
        self.bt_maximizar = QtWidgets.QPushButton(self.fr_header)
        self.bt_maximizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_maximizar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/credit-card.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_maximizar.setIcon(icon2)
        self.bt_maximizar.setObjectName("bt_maximizar")
        self.horizontalLayout.addWidget(self.bt_maximizar)
        self.bt_cerrar = QtWidgets.QPushButton(self.fr_header)
        self.bt_cerrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_cerrar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_cerrar.setIcon(icon3)
        self.bt_cerrar.setObjectName("bt_cerrar")
        self.horizontalLayout.addWidget(self.bt_cerrar)
        self.verticalLayout.addWidget(self.fr_header)
        self.fr_container = QtWidgets.QFrame(self.centralwidget)
        self.fr_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_container.setObjectName("fr_container")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fr_container)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fr_tabla = QtWidgets.QFrame(self.fr_container)
        self.fr_tabla.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_tabla.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_tabla.setObjectName("fr_tabla")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fr_tabla)
        self.verticalLayout_2.setContentsMargins(40, 11, 40, 40)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(10, 10, 0, 10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.lb_nombre_tabla = QtWidgets.QLabel(self.fr_tabla)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(20)
        self.lb_nombre_tabla.setFont(font)
        self.lb_nombre_tabla.setObjectName("lb_nombre_tabla")
        self.horizontalLayout_3.addWidget(self.lb_nombre_tabla)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.bt_menu = QtWidgets.QPushButton(self.fr_tabla)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bt_menu.setFont(font)
        self.bt_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/align-right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_menu.setIcon(icon4)
        self.bt_menu.setObjectName("bt_menu")
        self.horizontalLayout_3.addWidget(self.bt_menu)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.tb_container = QtWidgets.QTableWidget(self.fr_tabla)
        self.tb_container.setObjectName("tb_container")
        self.tb_container.setColumnCount(0)
        self.tb_container.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tb_container)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(10, 10, 0, 10)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lb_msgerror = QtWidgets.QLabel(self.fr_tabla)
        self.lb_msgerror.setMinimumSize(QtCore.QSize(250, 0))
        self.lb_msgerror.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_msgerror.setFont(font)
        self.lb_msgerror.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_msgerror.setObjectName("lb_msgerror")
        self.horizontalLayout_4.addWidget(self.lb_msgerror)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.bt_refrescar = QtWidgets.QPushButton(self.fr_tabla)
        self.bt_refrescar.setMaximumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bt_refrescar.setFont(font)
        self.bt_refrescar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/refresh-cw.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_refrescar.setIcon(icon5)
        self.bt_refrescar.setObjectName("bt_refrescar")
        self.horizontalLayout_4.addWidget(self.bt_refrescar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addWidget(self.fr_tabla)
        self.fr_menu = QtWidgets.QFrame(self.fr_container)
        self.fr_menu.setMinimumSize(QtCore.QSize(400, 0))
        self.fr_menu.setMaximumSize(QtCore.QSize(400, 16777215))
        self.fr_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_menu.setObjectName("fr_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.fr_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedw = QtWidgets.QStackedWidget(self.fr_menu)
        self.stackedw.setObjectName("stackedw")
        self.page_menu = QtWidgets.QWidget()
        self.page_menu.setObjectName("page_menu")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_menu)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 20, -1, 35)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.page_menu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.cb_tabla = QtWidgets.QComboBox(self.page_menu)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.cb_tabla.setFont(font)
        self.cb_tabla.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cb_tabla.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cb_tabla.setObjectName("cb_tabla")
        self.cb_tabla.addItem("")
        self.cb_tabla.addItem("")
        self.cb_tabla.addItem("")
        self.verticalLayout_4.addWidget(self.cb_tabla)
        spacerItem4 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem4)
        self.label_2 = QtWidgets.QLabel(self.page_menu)
        self.label_2.setMinimumSize(QtCore.QSize(60, 30))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.bt_agregar = QtWidgets.QPushButton(self.page_menu)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.bt_agregar.setFont(font)
        self.bt_agregar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/chevron-right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_agregar.setIcon(icon6)
        self.bt_agregar.setObjectName("bt_agregar")
        self.verticalLayout_4.addWidget(self.bt_agregar)
        self.bt_editar = QtWidgets.QPushButton(self.page_menu)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.bt_editar.setFont(font)
        self.bt_editar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_editar.setIcon(icon6)
        self.bt_editar.setObjectName("bt_editar")
        self.verticalLayout_4.addWidget(self.bt_editar)
        self.bt_eliminar = QtWidgets.QPushButton(self.page_menu)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.bt_eliminar.setFont(font)
        self.bt_eliminar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_eliminar.setIcon(icon6)
        self.bt_eliminar.setObjectName("bt_eliminar")
        self.verticalLayout_4.addWidget(self.bt_eliminar)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.label_3 = QtWidgets.QLabel(self.page_menu)
        self.label_3.setMinimumSize(QtCore.QSize(0, 40))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.bt_info = QtWidgets.QPushButton(self.page_menu)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.bt_info.setFont(font)
        self.bt_info.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_info.setIcon(icon6)
        self.bt_info.setObjectName("bt_info")
        self.verticalLayout_4.addWidget(self.bt_info)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.stackedw.addWidget(self.page_menu)
        self.page_agg_arbitro = QtWidgets.QWidget()
        self.page_agg_arbitro.setObjectName("page_agg_arbitro")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_agg_arbitro)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.fr_arbitro = QtWidgets.QFrame(self.page_agg_arbitro)
        self.fr_arbitro.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.fr_arbitro.setStyleSheet("QLabel{\n"
"    background-color: ;\n"
"    padding: ;\n"
"    color: black;\n"
"    font-family: \'Segoe UI\';\n"
"    text-decoration: ;\n"
"    font-size: 18px;\n"
"    font-weight: ;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #CCCCCC;\n"
"    padding: ;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 10pt;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #4D90FE;\n"
"    width: 200px; /* Ajusta el ancho al ser enfocado */\n"
"    height: 30px; /* Ajusta la altura al ser enfocado */\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: 1px solid #CCCCCC;\n"
"    padding: 1px;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 10pt;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: px;\n"
"    border-left: 1px solid #CCCCCC;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    /* Estilo cuando se presiona el botón de desplazamiento hacia abajo */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #CCCCCC;\n"
"    selection-background-color: #4D90FE; /* Color de fondo cuando se selecciona un elemento */\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #077110;\n"
"    color: #FFFFFF;\n"
"    padding: 10px 20px;\n"
"    border: none;\n"
"    border-top-right-radius: 20px;\n"
"    font-size: 17px; /* Tamaño de fuente */\n"
"    width: 150px; /* Ancho del botón */\n"
"    height: 22px; /* Altura del botón */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"    border-color: #000; /* Borde negro al hacer hover */\n"
"    color: black;\n"
"    border: 2px solid #000;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367d3b;\n"
"}\n"
"\n"
"\n"
"")
        self.fr_arbitro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_arbitro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_arbitro.setObjectName("fr_arbitro")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.fr_arbitro)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.fr_arbitro)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.lineEdit_nombre = QtWidgets.QLineEdit(self.fr_arbitro)
        self.lineEdit_nombre.setObjectName("lineEdit_nombre")
        self.verticalLayout_7.addWidget(self.lineEdit_nombre)
        self.label_5 = QtWidgets.QLabel(self.fr_arbitro)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.lineEdit_apellido = QtWidgets.QLineEdit(self.fr_arbitro)
        self.lineEdit_apellido.setObjectName("lineEdit_apellido")
        self.verticalLayout_7.addWidget(self.lineEdit_apellido)
        self.label_6 = QtWidgets.QLabel(self.fr_arbitro)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.lineEdit_pais = QtWidgets.QLineEdit(self.fr_arbitro)
        self.lineEdit_pais.setObjectName("lineEdit_pais")
        self.verticalLayout_7.addWidget(self.lineEdit_pais)
        self.label_7 = QtWidgets.QLabel(self.fr_arbitro)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.lineEdit_pasaporte = QtWidgets.QLineEdit(self.fr_arbitro)
        self.lineEdit_pasaporte.setObjectName("lineEdit_pasaporte")
        self.verticalLayout_7.addWidget(self.lineEdit_pasaporte)
        self.label_8 = QtWidgets.QLabel(self.fr_arbitro)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.lineEdit_inicio = QtWidgets.QLineEdit(self.fr_arbitro)
        self.lineEdit_inicio.setObjectName("lineEdit_inicio")
        self.verticalLayout_7.addWidget(self.lineEdit_inicio)
        self.label_9 = QtWidgets.QLabel(self.fr_arbitro)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.cb_reemplazo = QtWidgets.QComboBox(self.fr_arbitro)
        self.cb_reemplazo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cb_reemplazo.setObjectName("cb_reemplazo")
        self.cb_reemplazo.addItem("")
        self.cb_reemplazo.addItem("")
        self.cb_reemplazo.addItem("")
        self.verticalLayout_7.addWidget(self.cb_reemplazo)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem6)
        self.bt_aceptar_arbitro = QtWidgets.QPushButton(self.fr_arbitro)
        self.bt_aceptar_arbitro.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_aceptar_arbitro.setObjectName("bt_aceptar_arbitro")
        self.verticalLayout_8.addWidget(self.bt_aceptar_arbitro)
        self.bt_arbitro_regresar = QtWidgets.QPushButton(self.fr_arbitro)
        self.bt_arbitro_regresar.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/arrow-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_arbitro_regresar.setIcon(icon7)
        self.bt_arbitro_regresar.setObjectName("bt_arbitro_regresar")
        self.verticalLayout_8.addWidget(self.bt_arbitro_regresar)
        self.verticalLayout_9.addWidget(self.fr_arbitro)
        self.stackedw.addWidget(self.page_agg_arbitro)
        self.page_agg_partido = QtWidgets.QWidget()
        self.page_agg_partido.setObjectName("page_agg_partido")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_agg_partido)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.fr_partido = QtWidgets.QFrame(self.page_agg_partido)
        self.fr_partido.setStyleSheet("QLabel{\n"
"    background-color: ;\n"
"    padding: ;\n"
"    color: black;\n"
"    font-family: \'Segoe UI\';\n"
"    text-decoration: ;\n"
"    font-size: 18px;\n"
"    font-weight: ;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #CCCCCC;\n"
"    padding: ;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 10pt;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #4D90FE;\n"
"    width: 200px; /* Ajusta el ancho al ser enfocado */\n"
"    height: 30px; /* Ajusta la altura al ser enfocado */\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: 1px solid #CCCCCC;\n"
"    padding: 1px;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 10pt;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: px;\n"
"    border-left: 1px solid #CCCCCC;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    /* Estilo cuando se presiona el botón de desplazamiento hacia abajo */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #CCCCCC;\n"
"    selection-background-color: #4D90FE; /* Color de fondo cuando se selecciona un elemento */\n"
"}\n"
"\n"
"QTimeEdit {\n"
"    border: 1px solid #CCCCCC;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 10pt;\n"
"    color: #333333;\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #077110;\n"
"    color: #FFFFFF;\n"
"    padding: 10px 20px;\n"
"    border: none;\n"
"    border-top-right-radius: 20px;\n"
"    font-size: 17px; /* Tamaño de fuente */\n"
"    width: 150px; /* Ancho del botón */\n"
"    height: 22px; /* Altura del botón */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"    border-color: #000; /* Borde negro al hacer hover */\n"
"    color: black;\n"
"    border: 2px solid #000;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367d3b;\n"
"}\n"
"\n"
"QDateEdit {\n"
"    border: 1px solid #CCCCCC;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 10pt;\n"
"    color: #333333;\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"")
        self.fr_partido.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_partido.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_partido.setObjectName("fr_partido")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.fr_partido)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.fr_partido)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.lineEdit_id = QtWidgets.QLineEdit(self.fr_partido)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.verticalLayout_10.addWidget(self.lineEdit_id)
        self.label_11 = QtWidgets.QLabel(self.fr_partido)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11)
        self.cb_instacia = QtWidgets.QComboBox(self.fr_partido)
        self.cb_instacia.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cb_instacia.setObjectName("cb_instacia")
        self.cb_instacia.addItem("")
        self.cb_instacia.addItem("")
        self.cb_instacia.addItem("")
        self.cb_instacia.addItem("")
        self.cb_instacia.addItem("")
        self.verticalLayout_10.addWidget(self.cb_instacia)
        self.label_12 = QtWidgets.QLabel(self.fr_partido)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_10.addWidget(self.label_12)
        self.timeEdit_duracion = QtWidgets.QTimeEdit(self.fr_partido)
        self.timeEdit_duracion.setObjectName("timeEdit_duracion")
        self.verticalLayout_10.addWidget(self.timeEdit_duracion)
        self.label_13 = QtWidgets.QLabel(self.fr_partido)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_10.addWidget(self.label_13)
        self.dateEdit_fecha = QtWidgets.QDateEdit(self.fr_partido)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(10)
        self.dateEdit_fecha.setFont(font)
        self.dateEdit_fecha.setObjectName("dateEdit_fecha")
        self.verticalLayout_10.addWidget(self.dateEdit_fecha)
        self.label_14 = QtWidgets.QLabel(self.fr_partido)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_10.addWidget(self.label_14)
        self.timeEdit_hora = QtWidgets.QTimeEdit(self.fr_partido)
        self.timeEdit_hora.setObjectName("timeEdit_hora")
        self.verticalLayout_10.addWidget(self.timeEdit_hora)
        self.label_15 = QtWidgets.QLabel(self.fr_partido)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_10.addWidget(self.label_15)
        self.cb_arbitro = QtWidgets.QComboBox(self.fr_partido)
        self.cb_arbitro.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cb_arbitro.setObjectName("cb_arbitro")
        self.verticalLayout_10.addWidget(self.cb_arbitro)
        self.label_16 = QtWidgets.QLabel(self.fr_partido)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_10.addWidget(self.label_16)
        self.cb_estadio = QtWidgets.QComboBox(self.fr_partido)
        self.cb_estadio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cb_estadio.setObjectName("cb_estadio")
        self.verticalLayout_10.addWidget(self.cb_estadio)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem7)
        self.bt_aceptar_partido = QtWidgets.QPushButton(self.fr_partido)
        self.bt_aceptar_partido.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_aceptar_partido.setObjectName("bt_aceptar_partido")
        self.verticalLayout_11.addWidget(self.bt_aceptar_partido)
        self.bt_partido_regresar = QtWidgets.QPushButton(self.fr_partido)
        self.bt_partido_regresar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_partido_regresar.setText("")
        self.bt_partido_regresar.setIcon(icon7)
        self.bt_partido_regresar.setObjectName("bt_partido_regresar")
        self.verticalLayout_11.addWidget(self.bt_partido_regresar)
        self.verticalLayout_12.addWidget(self.fr_partido)
        self.stackedw.addWidget(self.page_agg_partido)
        self.page_agg_estadio = QtWidgets.QWidget()
        self.page_agg_estadio.setObjectName("page_agg_estadio")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.page_agg_estadio)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.fr_estadio = QtWidgets.QFrame(self.page_agg_estadio)
        self.fr_estadio.setStyleSheet("QLabel{\n"
"    background-color: ;\n"
"    padding: ;\n"
"    color: black;\n"
"    font-family: \'Segoe UI\';\n"
"    text-decoration: ;\n"
"    font-size: 18px;\n"
"    font-weight: ;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #CCCCCC;\n"
"    padding: ;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 10pt;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #4D90FE;\n"
"    width: 200px; /* Ajusta el ancho al ser enfocado */\n"
"    height: 30px; /* Ajusta la altura al ser enfocado */\n"
"}\n"
"\n"
"QSpinBox {\n"
"    border: 1px solid #CCCCCC;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 10pt;\n"
"    color: #333333;\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #077110;\n"
"    color: #FFFFFF;\n"
"    padding: 10px 20px;\n"
"    border: none;\n"
"    border-top-right-radius: 20px;\n"
"    font-size: 17px; /* Tamaño de fuente */\n"
"    width: 150px; /* Ancho del botón */\n"
"    height: 22px; /* Altura del botón */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"    border-color: #000; /* Borde negro al hacer hover */\n"
"    color: black;\n"
"    border: 2px solid #000;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367d3b;\n"
"}")
        self.fr_estadio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_estadio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_estadio.setObjectName("fr_estadio")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.fr_estadio)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_17 = QtWidgets.QLabel(self.fr_estadio)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_13.addWidget(self.label_17)
        self.lineEdit_nombre_ciudad = QtWidgets.QLineEdit(self.fr_estadio)
        self.lineEdit_nombre_ciudad.setObjectName("lineEdit_nombre_ciudad")
        self.verticalLayout_13.addWidget(self.lineEdit_nombre_ciudad)
        self.label_18 = QtWidgets.QLabel(self.fr_estadio)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_13.addWidget(self.label_18)
        self.lineEdit_ciudad = QtWidgets.QLineEdit(self.fr_estadio)
        self.lineEdit_ciudad.setObjectName("lineEdit_ciudad")
        self.verticalLayout_13.addWidget(self.lineEdit_ciudad)
        self.label_19 = QtWidgets.QLabel(self.fr_estadio)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_13.addWidget(self.label_19)
        self.spb_capacidad_max = QtWidgets.QSpinBox(self.fr_estadio)
        self.spb_capacidad_max.setObjectName("spb_capacidad_max")
        self.verticalLayout_13.addWidget(self.spb_capacidad_max)
        self.label_20 = QtWidgets.QLabel(self.fr_estadio)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_13.addWidget(self.label_20)
        self.spb_capacidad_hab = QtWidgets.QSpinBox(self.fr_estadio)
        self.spb_capacidad_hab.setObjectName("spb_capacidad_hab")
        self.verticalLayout_13.addWidget(self.spb_capacidad_hab)
        self.label_21 = QtWidgets.QLabel(self.fr_estadio)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_13.addWidget(self.label_21)
        self.spb_seguridad = QtWidgets.QSpinBox(self.fr_estadio)
        self.spb_seguridad.setObjectName("spb_seguridad")
        self.verticalLayout_13.addWidget(self.spb_seguridad)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        spacerItem8 = QtWidgets.QSpacerItem(20, 290, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem8)
        self.bt_aceptar_estadio = QtWidgets.QPushButton(self.fr_estadio)
        self.bt_aceptar_estadio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_aceptar_estadio.setObjectName("bt_aceptar_estadio")
        self.verticalLayout_14.addWidget(self.bt_aceptar_estadio)
        self.bt_estadio_regresar = QtWidgets.QPushButton(self.fr_estadio)
        self.bt_estadio_regresar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_estadio_regresar.setText("")
        self.bt_estadio_regresar.setIcon(icon7)
        self.bt_estadio_regresar.setObjectName("bt_estadio_regresar")
        self.verticalLayout_14.addWidget(self.bt_estadio_regresar)
        self.verticalLayout_15.addWidget(self.fr_estadio)
        self.stackedw.addWidget(self.page_agg_estadio)
        self.verticalLayout_3.addWidget(self.stackedw)
        self.horizontalLayout_2.addWidget(self.fr_menu)
        self.verticalLayout.addWidget(self.fr_container)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedw.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb_nombre_tabla.setText(_translate("MainWindow", "Nombre de la tabla"))
        self.bt_menu.setText(_translate("MainWindow", "Menu"))
        self.lb_msgerror.setText(_translate("MainWindow", "VALIDACIONES"))
        self.bt_refrescar.setText(_translate("MainWindow", "Refrescar "))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/icons/icons/users.svg\"/></p></body></html>"))
        self.cb_tabla.setItemText(0, _translate("MainWindow", "Árbitro"))
        self.cb_tabla.setItemText(1, _translate("MainWindow", "Partido"))
        self.cb_tabla.setItemText(2, _translate("MainWindow", "Estadio"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/icons/icons/clipboard.svg\"/></p></body></html>"))
        self.bt_agregar.setText(_translate("MainWindow", "Agregar"))
        self.bt_editar.setText(_translate("MainWindow", "Editar"))
        self.bt_eliminar.setText(_translate("MainWindow", "Eliminar"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/icons/icons/info.svg\"/></p></body></html>"))
        self.bt_info.setText(_translate("MainWindow", "Info.."))
        self.label_4.setText(_translate("MainWindow", "Nombre:"))
        self.label_5.setText(_translate("MainWindow", "Apellido:"))
        self.label_6.setText(_translate("MainWindow", "País:"))
        self.label_7.setText(_translate("MainWindow", "Pasaporte:"))
        self.label_8.setText(_translate("MainWindow", "Inicio (Año):"))
        self.label_9.setText(_translate("MainWindow", "Reemplazo:"))
        self.cb_reemplazo.setItemText(0, _translate("MainWindow", "New Item"))
        self.cb_reemplazo.setItemText(1, _translate("MainWindow", "New Item"))
        self.cb_reemplazo.setItemText(2, _translate("MainWindow", "New Item"))
        self.bt_aceptar_arbitro.setText(_translate("MainWindow", "Aceptar"))
        self.label_10.setText(_translate("MainWindow", "Id:"))
        self.label_11.setText(_translate("MainWindow", "Instancia:"))
        self.cb_instacia.setItemText(0, _translate("MainWindow", "Fase de grupos"))
        self.cb_instacia.setItemText(1, _translate("MainWindow", "Octavos de final"))
        self.cb_instacia.setItemText(2, _translate("MainWindow", "Cuartos de final"))
        self.cb_instacia.setItemText(3, _translate("MainWindow", "Semifinal"))
        self.cb_instacia.setItemText(4, _translate("MainWindow", "Final"))
        self.label_12.setText(_translate("MainWindow", "Duración:"))
        self.label_13.setText(_translate("MainWindow", "Fecha:"))
        self.label_14.setText(_translate("MainWindow", "Hora:"))
        self.label_15.setText(_translate("MainWindow", "Árbitro:"))
        self.label_16.setText(_translate("MainWindow", "Estadio:"))
        self.bt_aceptar_partido.setText(_translate("MainWindow", "Aceptar"))
        self.label_17.setText(_translate("MainWindow", "Nombre:"))
        self.label_18.setText(_translate("MainWindow", "Ciudad:"))
        self.label_19.setText(_translate("MainWindow", "Capacidad máxima:"))
        self.label_20.setText(_translate("MainWindow", "Capacidad habitada:"))
        self.label_21.setText(_translate("MainWindow", "Seguridad:"))
        self.bt_aceptar_estadio.setText(_translate("MainWindow", "Aceptar"))
import icons_rc
